---
title: "USGS Earthquake Hazards Program Map"
author: "Ramiro Alvite Díaz"
date: "2018-03-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```


[Earthquake Hazards Program API](https://earthquake.usgs.gov/fdsnws/event/1/) allows custom searches for earthquake information using a variety of parameters. 


```{r}
library(leaflet)
# load quakes data from USGS earthquakes API
quakes <- read.csv("http://earthquake.usgs.gov/fdsnws/event/1/query?starttime=1965-01-01T00:00:00&minmagnitude=5&format=csv&latitude=41.905740&longitude=12.488879&maxradiuskm=500&orderby=magnitude")

# make leaflet map using seismic risk data
seismic_map <- leaflet()

# set breaks for custom bins
breaks <- c(0,19,39,59,79,200)

# set palette
binpal <- colorBin("Reds", seismic_map$ACC_VAL, breaks)

# make multi-layered leaflet map with layer-switching control
# make choropleth map of seismic hazards
seismic <- seismic_map %>%
  setView(lng = 12.488879, lat = 41.905740, zoom = 5) %>%
  addProviderTiles("CartoDB.Positron", group = "CartoDB") %>% 
  addProviderTiles("Stamen.TonerLite", group = "Toner") %>%
  
  # add historical quakes
  addCircles(
    data=quakes, 
    radius = sqrt(10^quakes$mag)*50, 
    weight = 1.2, 
    color = "#000000", 
    fillColor ="#ffffff",
    fillOpacity = 0.3,
    popup = paste0("<strong>Magnitude: </strong>", quakes$mag, "</br>",
                   "<strong>Date: </strong>", format(as.Date(quakes$time), "%b %d, %Y")),
    group = "Quakes"
  ) %>%
  # add layers control
  addLayersControl(
    baseGroups = c("CartoDB", "Toner"),
    overlayGroups = "Quakes",
    options = layersControlOptions(collapsed = FALSE)
  )

# draw the map
seismic
```

